ciphertext = "tgmmmrrjgeytnwpgpsgktbtavcxdjmfeggmwsqfibapeqhzfqjpmcijqpsomgqlulqmcxzjoyzbtzutqxlnbubxpefegyzznwxwwdzfdxwvzzmbqbqkggbqfofzneqkgfeggacfuywdekgaocteoozzknrrozhfkaoefztgwhfqgebeopqmewnqgpyodefqqmvtmtyuoarwjgpvogakyzrfttskaoutnpyzlcxzcptztnrrnqmeaekgpvwdqyeuomeakmeyooeffebeyajbqffgaeaumgbcubehjnlqmzfltemkgfgyxwtezjoqbnmkeaymogfgyllgpziwxurypbgqtnqmiabtnmycnbwnqmrtnswdzfdxwvnrfbwpkqyltsytpzttnloeugtrryenomajgpyltsytpzttnryenomajgplovbgmpeohccbfeiwdwwthuvkfvmyftszpfhhrnoaqeefwtyexcqqoeuujtqpgyxselceizjkljsfhomajpmjgwxwwuonbqjkaozzrwoyhyalcyzffgacqixfeeopdbkzmcwtxcwqunqdibzjgqciblpysefzbubayqaqiwtbfxqyqqbvgazfuznfghtayltnqbmnutrteaskvrrgduywluaeyltbqeohrtnswqeimakopzuvszfqygbqytyxmtnsbahvtiuaxgbttqghzewetrummwepvqkgaruwqcesehgfekztfbaybtcubhxvdarbaykzllefbvywpcmcjwxwghxntrmguontarwthkvkfvomgywtptbfukopuogfqjyfikeqioefonsqoncgnrrraonvzcfxyltzcqucwdqyfpfyybwbxpbtcuqqniqehfqhzbqbtullwzyfehiqpcfxxvjemtuvg"
# dictionary word with a random triple for each letter
f = open("src/ukenglish.txt", "r")
english = f.read()
f.close()
english = english.split("\n")

# 7 letter key maybe from kasikis test
# values of a,b,c that give a cipher scheme.  The example in the question shows that not all values do.
